import React from 'react';
import Head from 'next/head';
import styles from '../../styles/Home.module.css';
import Image from 'next/image';

interface AppBarProps{
    children: any,
}

const AppBar = (props: AppBarProps) => {
    return (
        <div className={styles.container}>
            <Head>
                <title>오늘수거 분리배출 테스트</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={styles.context}>
            {props.children}
            </div>
            <footer className={styles.footer}>
                <a
                    href="https://repolarkorea.com/"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Created by{" "}
                    <span className={styles.logo}>
                    <Image
                        src="/onul.png"
                        alt="OnulSugo Logo"
                        width={130}
                        height={35}
                    />
                    </span>
                </a>
            </footer>
        </div>
    );
}

export default AppBar
