import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useState } from "react";

const Home: NextPage = () => {
  const [page, setPage] = useState(0);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.context}>
        <main className={styles.main}>
          <header className={styles.header}>
            <div className={styles.gauge}></div>
            {page == 0 ? (
              <div className={styles.gaugeText}>30%</div>
            ) : (
              <div className={styles.gaugeText}>50%</div>
            )}
          </header>
          <div className={styles.question}>
            <p className={styles.description}>Get started by editing </p>
          </div>
          <div className={styles.answer}>
            <div
              onClick={() => {
                setPage(1);
              }}
              className={styles.code}
            >
              pages/index.tsx
            </div>
            <div className={styles.code}>pages/index.tsx</div>
            <div className={styles.code}>pages/index.tsx</div>
            <div className={styles.code}>pages/index.tsx</div>
          </div>
        </main>

        <footer className={styles.footer}>
          <a
            href="https://repolarkorea.com/"
            target="_blank"
            rel="noopener noreferrer"
          >
            Created by{" "}
            <span className={styles.logo}>
              <Image
                src="/onul.png"
                alt="OnulSugo Logo"
                width={130}
                height={35}
              />
            </span>
          </a>
        </footer>
      </div>
    </div>
  );
};

export default Home;
