import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useState, useEffect } from "react";
import {useSpring, animated} from 'react-spring';

const Home: NextPage = () => {
  const [page, setPage] = useState(0);
  const [refresh, setRefresh] = useState(true);
  useEffect(() => {
    setRefresh(true);
  }, [page])

  const animation0 = useSpring({
    reset: refresh,
    from: {opacity:0.3,},
    to: {opacity:1, },
    config:{duration: 500,
    },
  })

  const animation1 = useSpring({
    reset: refresh,
    from: {x:-70},
    to: {x:0},
    config:{duration: 300},
  })

  const animation2 = useSpring({
    reset: refresh,
    from: {x:-70},
    to: {x:0},
    config:{duration: 500},
    
  })

  const animation3 = useSpring({
    reset: refresh,

    from: {x:-70},
    to: {x:0},
    config:{duration: 700},
    
  })

  const animation4 = useSpring({
    reset: refresh,
    from: {x:-70},
    to: {x:0},
    config:{duration: 900},
    
  })

  const pageClick = () => {
    page==1? setPage(2) :( page==2 ? setPage(3): (page==3? setPage(4): setPage(5)));
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>오늘수거 분리배출 테스트</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.context}>
        {page==0? (<main className={styles.main}>
          <div>오늘수거 분리배출 테스트</div>
          <div className={styles.code}
          onClick={() => {
            setPage(1);
          }}
          >시작하기</div>
        </main>): page==5? (
        <main className={styles.main}>
          <p className={styles.description}>
            당신의 결과는 어쩌구~~
          </p>
        </main>) :(
        <main className={styles.main}>
          <animated.div className={styles.header}
          style={{...animation0}}
          >
            <div className={styles.gauge} 
            style={{
              width: page==1?'20%': page==2? '40%' : page==3? '60%': '80%',
            }}
            />
            {page == 1 ? (
              <div className={styles.gaugeText}>20%</div>
            ) : (page==2? ( 
              <div className={styles.gaugeText}>40%</div>
            ):  
            (page==3? (<div className={styles.gaugeText}>60%</div>): (<div className={styles.gaugeText}>80%</div>))
          )}
          </animated.div>
          <div className={styles.question}>
            <p className={styles.description}>{page}번째 문제</p>
            <p className={styles.description}>문제문제문제문제 입니당</p>
          </div>
          <div className={styles.answer}>
            <animated.div
              onClick={() => {
                pageClick();
              }}
              className={styles.code}
              style={{
                ...animation1
              }}
            >
              1번째 답
            </animated.div>
            <animated.div className={styles.code}
            onClick={() => {
              pageClick();
            }}
            style={{
              ...animation2
            }}
            >2번째 답</animated.div>
            <animated.div className={styles.code}
            onClick={() => {
              pageClick();
            }}
            style={{
              ...animation3,
            }}
            >3번째 답</animated.div>
            <animated.div className={styles.code}
            onClick={() => {
              pageClick();
            }}
            style={{
              ...animation4
            }}
            >4번째 답</animated.div>
          </div>
        </main>)}

        <footer className={styles.footer}>
          <a
            href="https://repolarkorea.com/"
            target="_blank"
            rel="noopener noreferrer"
          >
            Created by{" "}
            <span className={styles.logo}>
              <Image
                src="/onul.png"
                alt="OnulSugo Logo"
                width={130}
                height={35}
              />
            </span>
          </a>
        </footer>
      </div>
    </div>
  );
};

export default Home;
